const stateobj = {
	timer: {
		clock: 0,
		current: null,
		elapsed: null,
		expectedFinish: null,
		addedTime: 0,
		startedAt: null,
		finishedAt: null,
		secondaryTimer: null,
		selectedEventId: null,
		duration: null,
		timerType: null,
		endAction: null,
	},
	playback: 'stop',
	timerMessage: { text: '', visible: false },
	publicMessage: { text: '', visible: false },
	lowerMessage: { text: '', visible: false },
	onAir: false,
	loaded: {
		selectedEventIndex: null,
		selectedEventId: null,
		selectedPublicEventId: null,
		nextEventId: null,
		nextPublicEventId: null,
		numEvents: 0,
	},
	titles: {
		titleNow: null,
		subtitleNow: null,
		presenterNow: null,
		noteNow: null,
		titleNext: null,
		subtitleNext: null,
		presenterNext: null,
		noteNext: null,
	},
	titlesPublic: {
		titleNow: null,
		subtitleNow: null,
		presenterNow: null,
		noteNow: null,
		titleNext: null,
		subtitleNext: null,
		presenterNext: null,
		noteNext: null,
	},
	events: [{ id: 'noEvents', label: 'No events found' }],
}

export { stateobj }
